# This is a basic workflow to help you get started with Actions

name: Publish Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the v4 branch
on: push
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.wplms.io
        ftp-username: documentation@wplms.io
        ftp-password: L0.2LIyQ@7AN
